### ISSUE TITLE
[BUG] Cannot build code. Receiving an error from forge artifact

### ISSUE THREAD

**Issue by koenigstag** [Traister101/Sacks-and-Such#2]
**Describe the bug**
When building the code receive an error:
`Error getting artifact: net.minecraftforge:forge:1.20.1-47.1.3_mapped_official_1.20.1:null@jar from MinecraftUserRepo`

**To Reproduce**
- Run `gradlew build` twice

**Comment by koenigstag** [comment]
Changed the forge version to 47.3.0 (in gradle.properties) and got a successful build.
But the next build got the described error again.

**Comment by Traister101** [comment]
Why exactly is this being reported to me? If you changed stuff and it broke the build system that's not my problem.

**Comment by Traister101** [comment]
Can't reproduce and you haven't answered why whatever happens with your fork is my problem so I'm closing this.
