### ISSUE TITLE
[BUG]Copy item

### ISSUE THREAD

**Issue by Sigmenzzz** [Traister101/Sacks-and-Such#3]
Copy item when pick them with containers.
it seems that it hasnot fixed well already...

Video:https://youtu.be/FB7xchGVLKI

- Minecraft version: 1.20.1
- Mod version: 1.1
- Forge version: 47.2.30
- TFC version: 3.2.7
- Curios version: 5.10.0

**Comment by Traister101** [comment]
Well that really sucks. Alright appreciate the report. You'll get a notification/email when this is fixed & a release will follow shortly.
